import type { Metadata } from "next";
import LegalPage, {
  LegalP,
  LegalList,
  LegalStrong,
  type LegalSection,
} from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service — Novi",
  description:
    "The terms that govern your use of Novi, our AI mentor and student success platform.",
};

const sections: LegalSection[] = [
  {
    id: "acceptance",
    title: "Acceptance of These Terms",
    content: (
      <>
        <LegalP>
          Welcome to <LegalStrong>Novi</LegalStrong> (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of our
          website, mobile applications, and services (together, the &quot;Service&quot;),
          including the Novi AI mentor, career and university explorers,
          personalized roadmaps, and parent dashboards.
        </LegalP>
        <LegalP>
          By creating an account, accessing, or using the Service, you agree to
          be bound by these Terms. If you are using the Service on behalf of a
          minor, you affirm that you are the parent or legal guardian of that
          minor and agree to these Terms on their behalf. If you do not agree,
          please do not use the Service.
        </LegalP>
      </>
    ),
  },
  {
    id: "who-can-use",
    title: "Who Can Use Novi",
    content: (
      <>
        <LegalP>
          The Service is intended for students typically in secondary school
          and beyond, their parents and guardians, and schools or universities
          that partner with Novi.
        </LegalP>
        <LegalList
          items={[
            "Students must be at least 13 years old, or the minimum age required by applicable law in your region, to use the Service.",
            "Users under 18 must have permission from a parent or legal guardian.",
            "You may not use the Service if you are barred from it by applicable law, or if we have previously terminated your access.",
          ]}
        />
      </>
    ),
  },
  {
    id: "accounts",
    title: "Creating an Account",
    content: (
      <>
        <LegalP>
          Some features require an account. When you create one, you agree to
          provide accurate and complete information and to keep it up to date.
          You are responsible for safeguarding your login credentials and for
          all activity that occurs under your account.
        </LegalP>
        <LegalP>
          You must notify us immediately if you believe your account has been
          compromised. We may, at our discretion, refuse to offer the Service
          to any person or entity, and may change or discontinue any feature at
          any time.
        </LegalP>
      </>
    ),
  },
  {
    id: "the-service",
    title: "The Novi Service",
    content: (
      <>
        <LegalP>
          Novi helps students discover who they are, explore careers and
          universities, and build a plan toward their goals. The Service
          includes, among other things:
        </LegalP>
        <LegalList
          items={[
            "AI mentor conversations that answer questions and provide guidance.",
            "Career DNA profiling and career recommendations.",
            "University search, comparison, and requirement tracking.",
            "Personalized, evolving roadmaps and progress dashboards.",
            "Parent accounts with progress and insight views.",
          ]}
        />
      </>
    ),
  },
  {
    id: "ai-mentor-guidance",
    title: "AI Mentor Guidance & Disclaimers",
    content: (
      <>
        <LegalP>
          The Novi AI mentor is an educational tool, not a licensed
          counselor, education consultant, psychologist, or financial
          advisor. Its responses are generated by machine learning and may be
          incomplete, inaccurate, or out of date.
        </LegalP>
        <LegalList
          items={[
            "Guidance and recommendations are general information and should be verified before making important decisions.",
            "Novi does not guarantee admission to any university, program, scholarship, or job, regardless of the recommendations provided.",
            "Always confirm deadlines, requirements, and policies directly with the relevant university, program, or counselor.",
          ]}
        />
        <LegalP>
          The Service may occasionally generate responses that are unexpected
          or incorrect. Please use your judgment and seek input from trusted
          adults and professionals.
        </LegalP>
      </>
    ),
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    content: (
      <>
        <LegalP>
          You agree not to misuse the Service. By way of example, you must not:
        </LegalP>
        <LegalList
          items={[
            "Impersonate another person or create accounts with false information.",
            "Upload unlawful, harmful, threatening, abusive, or harassing content.",
            "Attempt to access, probe, or disrupt the Service, its servers, or connected networks.",
            "Reverse engineer, decompile, or attempt to extract the source code of the Service.",
            "Scrape, harvest, or copy data from the Service without our prior written consent.",
            "Use the Service to generate content that is unlawful, discriminatory, or that violates the rights of others.",
          ]}
        />
        <LegalP>
          We may suspend or terminate access for any conduct we believe
          violates these Terms or is otherwise harmful to the Service, other
          users, or third parties.
        </LegalP>
      </>
    ),
  },
  {
    id: "user-content",
    title: "User Content You Provide",
    content: (
      <>
        <LegalP>
          You retain ownership of the content you submit to the Service, such
          as prompts, journal entries, goals, and profile answers (&quot;User
          Content&quot;). By submitting User Content, you grant Novi a
          non-exclusive, worldwide, royalty-free license to use, store,
          display, and process it solely to operate, improve, and personalize
          the Service.
        </LegalP>
        <LegalP>
          You are solely responsible for the User Content you submit and
          represent that you own or have the necessary rights to it. We do not
          claim ownership of your User Content.
        </LegalP>
      </>
    ),
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    content: (
      <>
        <LegalP>
          The Service, including its software, designs, logos, text,
          graphics, and the Novi AI models and outputs, is owned by Novi or
          its licensors and is protected by copyright, trademark, and other
          laws.
        </LegalP>
        <LegalP>
          We grant you a limited, non-exclusive, non-transferable,
          revocable license to use the Service for your personal,
          non-commercial use, subject to these Terms. No other rights are
          granted.
        </LegalP>
      </>
    ),
  },
  {
    id: "subscriptions-payments",
    title: "Subscriptions & Payments",
    content: (
      <>
        <LegalP>
          The Service may be offered free of charge or through paid plans. If
          you purchase a subscription, you agree to pay all fees, taxes, and
          charges associated with your account.
        </LegalP>
        <LegalP>
          Subscription fees are generally charged in advance and are
          non-refundable except where required by law. We may change fees or
          introduce new fees with reasonable notice. If you cancel your
          subscription, your access continues until the end of the current
          billing period.
        </LegalP>
      </>
    ),
  },
  {
    id: "third-party",
    title: "Third-Party Services",
    content: (
      <>
        <LegalP>
          The Service may link to or integrate with third-party websites,
          tools, and content. We do not control and are not responsible for
          such third parties. Your use of third-party services is subject to
          their own terms and policies.
        </LegalP>
      </>
    ),
  },
  {
    id: "warranty-disclaimer",
    title: "Disclaimer of Warranties",
    content: (
      <>
        <LegalP>
          The Service is provided on an &quot;as is&quot; and &quot;as available&quot; basis,
          without warranties of any kind, whether express or implied,
          including implied warranties of merchantability, fitness for a
          particular purpose, and non-infringement. We do not warrant that the
          Service will be uninterrupted, secure, or error-free, or that any
          AI-generated content will be accurate or reliable.
        </LegalP>
      </>
    ),
  },
  {
    id: "limitation-liability",
    title: "Limitation of Liability",
    content: (
      <>
        <LegalP>
          To the maximum extent permitted by law, Novi and its officers,
          directors, employees, and agents will not be liable for any indirect,
          incidental, special, consequential, or punitive damages — including
          lost profits, data, or goodwill — arising out of or related to your
          use of the Service.
        </LegalP>
        <LegalP>
          Our total aggregate liability for all claims relating to the Service
          will not exceed the greater of the amount you paid us for the Service
          in the twelve (12) months preceding the claim, or one hundred dollars
          ($100).
        </LegalP>
      </>
    ),
  },
  {
    id: "indemnification",
    title: "Indemnification",
    content: (
      <>
        <LegalP>
          You agree to indemnify and hold harmless Novi and its affiliates,
          officers, directors, employees, and agents from and against any
          claims, damages, liabilities, and expenses (including reasonable
          attorneys&apos; fees) arising out of your use of the Service, your User
          Content, or your violation of these Terms or applicable law.
        </LegalP>
      </>
    ),
  },
  {
    id: "termination",
    title: "Termination",
    content: (
      <>
        <LegalP>
          You may stop using the Service at any time and delete your account
          through your settings or by contacting us. We may suspend or
          terminate your access to the Service at any time, with or without
          notice, for any conduct we believe violates these Terms or harms the
          Service or its users.
        </LegalP>
        <LegalP>
          Sections that by their nature should survive termination — including
          warranty disclaimers, limitation of liability, indemnification, and
          governing law — will survive any termination of these Terms.
        </LegalP>
      </>
    ),
  },
  {
    id: "governing-law",
    title: "Governing Law & Disputes",
    content: (
      <>
        <LegalP>
          These Terms are governed by the laws of the State of Delaware,
          United States, without regard to its conflict-of-law principles. Any
          dispute arising from these Terms or the Service will be subject to
          the exclusive jurisdiction of the state and federal courts located in
          Delaware.
        </LegalP>
        <LegalP>
          To the extent permitted by law, each party waives the right to a jury
          trial and to participate in any class action in connection with any
          dispute arising under these Terms.
        </LegalP>
      </>
    ),
  },
  {
    id: "changes",
    title: "Changes to These Terms",
    content: (
      <>
        <LegalP>
          We may revise these Terms from time to time. When we make material
          changes, we will update the &quot;Last updated&quot; date and notify you where
          appropriate. Continued use of the Service after changes take effect
          constitutes acceptance of the revised Terms.
        </LegalP>
      </>
    ),
  },
  {
    id: "contact",
    title: "Contact Us",
    content: (
      <>
        <LegalP>
          If you have questions about these Terms, please contact us at:
        </LegalP>
        <LegalList
          items={[
            <>
              <LegalStrong>Email:</LegalStrong> support@novi.ai
            </>,
            <>
              <LegalStrong>Subject line:</LegalStrong> &quot;Terms&quot;
            </>,
          ]}
        />
      </>
    ),
  },
];

export default function TermsOfServicePage() {
  return (
    <LegalPage
      badge="Legal"
      headline={
        <>
          Simple, fair terms
          <br />
          for everyone.
        </>
      }
      intro="These Terms of Service set out the rules for using Novi — what you agree to, what we promise, and how we work together to keep Novi useful, safe, and supportive."
      lastUpdated="September 13, 2026"
      sections={sections}
    />
  );
}